version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
  nextcloud_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/FileServer

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - nextcloud_data:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8195:8080 # change the port on the left side if it's already in use on your host system.
    environment:
      - APACHE_PORT=11000  # change this port number if 11000 is already in use on your host system.
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_TRUSTED_DOMAINS=< nextcloud.your-super-domain.com > < proxy host IP > # Your domain name + proxy host IP
      - TRUSTED_PROXIES=< proxy host IP > # proxy host IP
